Repository wellFoundedDevelopers/ComputerScience, pull requests merged in 2023-03, with the labels that each got.

#13 [이지민] 4주차 - Binary Heap
  DataStructure/BinaryHeap/jimin/BinaryHeap.md
Labels: 자료

#16 발표자 뽑는 로직 변경(가중치 할당)
  pick.py
Labels: enhancement

#18 [장희직] 5주차 - Red-Black Tree 자료
  DataStructure/Red-BlackTree/heejik/Red-Black Tree.md
Labels: 자료

#19 [소병희] 5주차 - Red-Black Tree
  DataStructure/Red-BlackTree/byeonghee/Red-BlackTree.md
  DataStructure/Red-BlackTree/byeonghee/RedBlackTree.kt
Labels: 자료, 코드

#20 [소병희] 4주차 - BinaryHeap
  DataStructure/BinaryHeap/byeonghee/BinaryHeap.md
Labels: 자료

#21 [전현수] - 5주차 Red-Black Tree
  DataStructure/Red-Black Tree/hyunsoo/Red-Black Tree.md
Labels: 자료

#22 [장희직] - 6주차 B+ Tree 자료
  DataStructure/B+Tree/heejik/B+Tree.md
Labels: 자료

#23 [전현수] - 6주차 B Tree, B+Tree 추가
  DataStructure/B+Tree/hyunsoo/B Tree.md
  DataStructure/B+Tree/hyunsoo/B+Tree.md
Labels: 자료

#24 [이지민] 5주차 - Red-Black Tree
  DataStructure/Red-BlackTree/jimin/Red-Black Tree.md
Labels: 자료

#25 [이지민] 6주차 B-Tree / B+Tree
  DataStructure/B+Tree/jimin/B-Tree&B+Tree.md
Labels: 자료

#26 [장희직] - 7주차 OSI 7계층 자료
  DataStructure/OSI-7Layer/heejik/OSI-7Layer.md
Labels: 자료
